### ISSUE TITLE
[Vaclavyzer] Analyzers which work on literal strings to validate proper characters are used

### ISSUE THREAD

**Issue by Therzok** [Therzok/MonoDevelop.Analyzers#18]
i.e. `...` -> `\u2026`

**Comment by Therzok** [comment]
cc @vancura did you have a list of these kind of text changes?

**Comment by vancura** [comment]
Sure. First, this needs to work _inside_ strings only.

* `number x number` → `number × number` (× = `\u00D7`)
* `numberxnumber` → `number×number` (× = `\u00D7`)
* `string - string` → `string – string` (– = `\u2013`)

This could be enough for now, let's start lightly.

**Comment by vancura** [comment]
Related: https://gist.github.com/vancura/27fad9793840ceabae14

**Comment by Therzok** [comment]
Thanks!

**Comment by Therzok** [comment]
Fixed via https://github.com/Therzok/MonoDevelop.Analyzers/commit/615a6ead92e64c3eb7edfce4a740c818123dd804
